name: Reviewdog

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

env:
  MIX_ENV: dev

jobs:
  credo:
    name: Credo
    runs-on: ubuntu-latest

    container:
      image: elixir:1.10.2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Dependencies
        uses: actions/cache@v1
        id: cache-deps
        with:
          path: deps
          key: deps-${{ env.MIX_ENV }}-v${{ env.ELIXIR_VERSION }}-otp-${{ env.OTP_VERSION }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            deps-${{ env.MIX_ENV }}-v${{ env.ELIXIR_VERSION }}-otp-${{ env.OTP_VERSION }}-

      - name: Ensure Hex & Rebar are installed
        run: |
          mix local.rebar --force
          mix local.hex --force

      - name: Get Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Run Credo
        uses: red-shirts/reviewdog-action-credo@v1
        with:
          github_token: ${{ secrets.github_token }}
          info: info
          reporter: github-pr-review

  misspell:
    name: Misspell
    runs-on: ubuntu-latest

    steps:
      - name: Check out code.
        uses: actions/checkout@v1

      - name: Run Misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review

